### ISSUE TITLE
Getting “ImportError: cannot import name ‘HttpInputChannel’

### ISSUE THREAD

**Issue by prabur90** [botfront/rasa-addons#33]
We are using rasa-core, rasa-nlu and Flask. We are getting the below error. Could you please help us to resolve this issue?

[chatbot.zip](https://github.com/mrbot-ai/rasa-addons/files/2693379/chatbot.zip)

We are using the below versions.
rasa                               0.0.5
rasa-core                       0.12.3
rasa-core-sdk                0.12.1
rasa-nlu                         0.13.8

**Comment by duckingbread** [comment]
can someone help with this?
