### ISSUE TITLE
TEST CASE INTERRUPTED

### ISSUE THREAD

**Issue by abhishakvarshney** [botfront/rasa-addons#35]
Rasa Addons version (e.g. 0.5.0): 0.5.5
Rasa Core version (e.g. 0.12.x): 0.12.2
Describe the problem:

I am getting following logs when I run test case:
```
## CHITCHAT.GREET
* /chitchat.greet

  - Sorry, I am unable to understand that. (exp: utter_greet)
TEST CASE INTERRUPTED)

## CHITCHAT.GOODBYE
* /chitchat.goodbye

  - I like to know what Im talking about, dont know what you sent...so not gonna say anything. (exp: utter_goodbye)
TEST CASE INTERRUPTED)
```
Can you help me to resolve this issue?

**Comment by Diwahars** [comment]
@abhishakvarshney : Can you share your test case code? Im just beginning to use automated test cases for rasa?

**Comment by abhishakvarshney** [comment]
No @znat that was logs which I got on terminal my test_case file is something like:
```
## chitchat.greet
* chitchat.greet
  - utter_greet

## chitchat.goodbye
* chitchat.goodbye
  - utter_goodbye
```
so that's not the solution.
