### ISSUE TITLE
rasa-addons not working when form action is in active

### ISSUE THREAD

**Issue by akilesh96** [botfront/rasa-addons#36]

**Comment by akilesh96** [comment]
`disambiguation_policy:
  trigger: $0 < 4 * $1
  type: suggest
  max_suggestions: 2
  slot_name: parse_data
  display:
    text_template: utter_disamb_text
    button_title_template_prefix: utter_disamb

input_validation:
  - after: utter_ask_skillset
    regex: false
    expected:
      - intents:
        - candidate_details
        entities:
        - skillset
      - intents:
        - skillset_fetch
        entities:
        - skillset
      - intents:
        - job_opening
        entities:
        - skillset
    error_template: utter_affirm`

This is my rules.yml

**Comment by znat** [comment]
I'm aware of that @akilesh96 , but isnt't it better to rely on the FormAction validation when using forms?
