### ISSUE TITLE
FAQ bot not working

### ISSUE THREAD

**Issue by AnandDev8** [botfront/rasa-addons#38]
Rasa Addons version (e.g. 0.5.9): 
Rasa Core version (e.g. 0.12.1): 
Describe the problem:
I am just trying on building an FAQ bot and my files are as follows
*** nlu_data.md**
intent: greet
- hai
- hey
intent: bye
- bye bye
- bye for now
intent: faq.add_money
- how to add money to this bank
- i would like to add money to this bank
intent: faq.create_account
- how can i create an account
- i want to create account

**domain.yml**
intent
- faq.create_account
- faq.add_money
- bye
- greet
template
- utter_greet
   text:''Hello there, how can I help you?"
actions
 - utter_greet
 - action_faq
 
**stories.yml**
## FAQ
* faq
  - action_faq
## story 1
* greet
  - utter_greet
## story 2
* greet
 - utter_greet
* faq
  - action_faq
* thankyou
  - utter_thankyou
## story 3
* thankyou
 - utter_thankyou

**Bot Service load agent contains**

agent = SuperAgent.load(self.dialogpath, interpreter=self.nluPath,action_endpoint=action_endpoint,rules='rules.yml')

**rules.yml**
intent_substitutions:
  - intent: (faq.*)
    with: faq
    entities:
      add:
      - name: intent
        value: '{intent}'

But i am not able to make hit on my action endpoint
My results are as below
UserUttered(text: hi, intent: {'name': 'greet', 'confidence': 0.9338731169700623}, entities: [])
UserUttered(text: hi, intent: {'name': 'greet', 'confidence': 0.9338731169700623}, entities: [])
[{'recipient_id': 'Rasa', 'text': 'Hello there, how can I help you?'}]

It is working fine but if i gave any FAQ based question
UserUttered(text: how can i create an account, intent: {'name': 'faq', 'confidence': 0.965238094329834}, entities: [{'entity': 'intent', 'value': faq.create_account'}])
UserUttered(text: None, intent: {}, entities: [])

i am not getting any hit on my action endpoint and UserUtterred is getting None

Is there any changes that i should need to do?
I would be really helpful if someone can find a solution for this problem

Thanks 
Anand S.Menon

**Comment by znat** [comment]
Your intent names must start with faq.*

Le sam. 6 avr. 2019 11 h 58, Anand S Menon <notifications@github.com> a
écrit :

**Comment by AnandDev8** [comment]
Hi @znat 
Thanks for the response :)
It would be really great if you could provide an example for faq.*
As you can see in my nlu_data.md file i have given intent names like 
**intent: faq.add_money**
  how to add money to this bank
  i would like to add money to this bank
**intent: faq.create_account**
  how can i create an account
  i want to create account
Is there any thing wrong with this format as i thought faq.* means faq.(name of the faq intent)

I would be really helpful if you have any example project in github which i could refer to

Thanks

**Comment by znat** [comment]
faq.greet, faq.thanks, faq.bye,... Just start your intent names with faq.

Le dim. 7 avr. 2019 10 h 20, Anand S Menon <notifications@github.com> a
écrit :

**Comment by AnandDev8** [comment]
I have given every intents as faq.greet,faq.bye..etc but still not getting any hit on the actions endpoint
**Issue**
UserUttered(text: hi, intent: {'name': 'faq', 'confidence': 0.9547087550163269}, entities: [{'entity': 'intent', 'value': 'faq.greet'}])
UserUttered(text: None, intent: {}, entities: [])
