### ISSUE TITLE
Add from_credentials to WebchatInput

### ISSUE THREAD

**Issue by ijufumi** [botfront/rasa-addons#55]
**Is your feature request related to a problem? Please describe.**
When I implemented webchat using WebchatInput, "Access-Control-Allow-Origin cannot contain more than one origin" error was happened.
The cause of this problems is below codes
```
sio = AsyncServer(
      async_mode="sanic", cors_allowed_origins=self.cors_allowed_origins
)
``` 
`self.cors_allowed_origins` is always `*`.
But to enable CORS in AsyncServer, need to set `[]` to `cors_allowed_origins`.

see
https://github.com/miguelgrinberg/python-socketio/issues/205#issuecomment-493769183

**Describe the solution you'd like**
I think that need to set `[]` to `cors_allowed_origins` if necessary.
I added from_credentials function to WebchatInput class.

**Comment by pheel** [comment]
Thanks!
