### ISSUE TITLE
Duckling component fails

### ISSUE THREAD

**Issue by znat** [botfront/rasa-addons#57]
Rasa Addons version (e.g. 0.5.0): 
Rasa Core version (e.g. 0.12.x): 
Describe the problem:
<img width="1192" alt="Capture d’écran 2020-03-16 à 13 19 50" src="https://user-images.githubusercontent.com/3694634/76783808-f1503480-6788-11ea-8597-c89841742298.png">

**Comment by pheel** [comment]
@znat What's the value of `rasa_addons.nlu.components.ducking_http_extractor` over `rasa.nlu.extractors.duckling_http_extractor`?

**Comment by znat** [comment]
Support for timezone and reftime in the query string. The Rasa one only supports setting those as component params, but a timezone can be user specific. It relies on the fact that query params are passed to all components. I had submitted a PR in the past but they were just transitioning to rasa 1.0 and by the time they looked at it it was not mergeabke anymore
