### ISSUE TITLE
Fields option from Credentials not explain in Documentation

### ISSUE THREAD

**Issue by alebeta90** [botfront/rasa-addons#60]
Hi,

Am using the Facebook connector, and want to test the multilanguage option. I saw a problem about permissions from FB graphql later on I saw read the connector file https://github.com/botfront/rasa-addons/blob/master/rasa_addons/core/channels/facebook_messenger.py#L31

And I found out, there is a fields field that should be define in the credentials configuration. After I define in my credentials for facebook connector the field fields with value locale, I'm successfully receiving the user language, for example

fields: "locale"

Dont know if it should work without specifying that in the credentials or if it is really missing from botfront documentation.

thanks

**Comment by znat** [comment]
By default all fields are passed, which may break if you don't have sufficient permissions. If you only can use a subset of the fields you can list them in `fields`

**Comment by alebeta90** [comment]
Hi @znat 

thanks for the clarification, that make sense, it was the problem I had, but defining the fields in the credentials config solved the problem.

thanks
