### ISSUE TITLE
What is Gazettes? in the repo

### ISSUE THREAD

**Issue by NomanSaleem4** [botfront/rasa-addons#61]
Hi I want to know what is Gazzettes? [https://github.com/botfront/rasa-addons/blob/master/rasa_addons/nlu/components/gazette.py] (url) what is its purpose and how can we use it. Thanks

**Comment by pheel** [comment]
Some explanation is given [in the Botfront docs](https://botfront.io/docs/rasa/nlu/training/#gazettes).

**Comment by NomanSaleem4** [comment]
Thanks
