### ISSUE TITLE
TypeError: nlg_request_format() got multiple values for keyword argument 'language' when using BotfrontMappingPolicy

### ISSUE THREAD

**Issue by ElBullet** [botfront/rasa-addons#64]
# Versions

botfront: 'botfront/botfront:v0.22.0'
botfront-api: 'botfront/botfront-api:v0.22.0'
rasa: 'botfront/rasa-for-botfront:v1.9.0-bf.3'
duckling: 'botfront/duckling:latest'
mongo: 'mongo:latest'
actions: 'rasa/rasa-sdk:1.9.0'

# Policy

policies:
  - name: FormPolicy
  - name: FallbackPolicy
  - name: AugmentedMemoizationPolicy
  - name: MemoizationPolicy
  - name: rasa_addons.core.policies.BotfrontMappingPolicy
    triggers:
      - trigger: '^map\..+'
        action: 'action_botfront_mapping'

# Logs

botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa_addons.core.policies.mapping  - Triggers: ^map\..+
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa_addons.core.policies.mapping  - The predicted intent 'map.desc_admincenter' is being  handled by BotfrontMappingPolicy.
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_4_BotfrontMappingPolicy
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.processor  - Predicted next action 'action_botfront_mapping' with confidence 1.00.
botfront-rasa   | 2020-04-23 07:57:48 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_botfront_mapping'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
**botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.processor  - nlg_request_format() got multiple values for keyword argument 'language'
botfront-rasa   | Traceback (most recent call last):
botfront-rasa   |   File "/opt/venv/lib/python3.6/site-packages/rasa/core/processor.py", line 627, in _run_action
botfront-rasa   |     events = await action.run(output_channel, nlg, tracker, self.domain)
botfront-rasa   |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
botfront-rasa   |     return self.gen.send(None)
botfront-rasa   |   File "/opt/venv/lib/python3.6/site-packages/rasa_addons/core/actions/action_botfront_mapping.py", line 35, in run
botfront-rasa   |     language=tracker.latest_message.metadata["language"],
botfront-rasa   |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
botfront-rasa   |     return self.gen.send(None)
botfront-rasa   |   File "/opt/venv/lib/python3.6/site-packages/rasa_addons/core/nlg/graphql.py", line 121, in generate
botfront-rasa   |     projectId=os.environ.get("BF_PROJECT_ID"),
botfront-rasa   | TypeError: nlg_request_format() got multiple values for keyword argument 'language'**
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.processor  - Action 'action_botfront_mapping' ended with events '[]'.
botfront-rasa   | 2020-04-23 07:57:48 DEBUG    rasa.core.processor  - Current slot values:
botfront-rasa   |       disambiguation_message: None
botfront-rasa   |       fallback_language: de

**Comment by pheel** [comment]
@ElBullet thanks for the report, I'll look into it.
